NONAME_ROLE = 'noname'
USER_ROLE = 'user'
ADMIN_ROLE = 'admin'

SELECT_ACTION = 0
WAIT_DOLLAR_DEPOSIT = 1
WAIT_RUBLE_DEPOSIT = 2

DEPOSIT_ACTION = 'deposit'
WITHDRAW_ACTION = 'withdraw'

BOT_START_DATE = '2023-08-21'
